In [7]:
import msmhelper as mh
import numpy as np

# create random trajectory
traj = np.random.randint(4, size=10000)

Create a trajectory instance

In [8]:
traj = mh.StateTraj(traj)

In [9]:
traj

StateTraj([array([1, 3, 0, ..., 3, 2, 3])])

In [10]:
traj.nstates

4

In [11]:
traj.states

array([0, 1, 2, 3])

In [12]:
# estimate Markov state model
traj.estimate_markov_model(2)

(array([[0.2522881 , 0.24990052, 0.25507362, 0.24273776],
        [0.24714679, 0.25462416, 0.24872098, 0.24950807],
        [0.24598716, 0.26083467, 0.24598716, 0.24719101],
        [0.26019576, 0.25081566, 0.24755302, 0.24143556]]),
 array([0, 1, 2, 3]))